name: Publish Maven Package

on:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: "adopt"

      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: clean publish
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
